<?php
@ini_set("session.bug_compat_warn", 0);
@ini_set("register_globals", 0);
@ini_set("memory_limit", -1);
@ini_set('default_charset','utf8');
@ini_set("max_execution_time", 300);
@ini_set("error_reporting", E_ALL & ~E_DEPRECATED);
@ini_set("display_errors", 1);

date_default_timezone_set('America/Sao_Paulo');

if (!session_id())
	session_start();

$RODAPE = "<center><font face='Verdana, Arial, Helvetica, sans-serif' color='#000066' size='2'><b>Sistema desenvolvido por:</b></font><br/><font face='Verdana, Arial, Helvetica, sans-serif' size='1'>FUTURIZE - Tecnologia em Sistemas de Informação LTDA.</font></center>";

$keycrypt = "Jesus is The Awesome God";

$USU_FUTURIZE = 1;//Usuário padrão nas prefeituras

$arrCompetencias = array(2015);

$BTNSALVARNOVO = "Salvar+Novo";
$BTNSALVARSAIR = "Salvar+Sair";
$BTNSALVAR     = "Salvar";

$VALBTNSALVARNOVO = "Salvar Novo";
$VALBTNSALVARSAIR = "Salvar Sair";
$VALBTNSALVAR     = "Salvar";

$TLU_PAGINAINICIAL   = 1;
$TLU_LOGININVALIDO   = 2;
$TLU_LOGINVALIDO     = 3;
$TLU_ALTERARSENHA    = 4;
$TLU_ACESSOINVALIDO  = 5;
$TLU_SQLINJECTION    = 6;
$TLU_ERRO404         = 7;
$TLU_ERRO403         = 8;

$SUS_AGUARLIBPREFEITURA = 1;
$SUS_REGULAR            = 2;
$SUS_INATIVO            = 3;

//Prefeituras
$PRE_EXEMPLOMG = 523418;

//Permissões
$PER_CADASTROFAMILIAS                           = 1;
$PER_CADASTROFAMILIASINSERIR                    = 2;
$PER_CADASTROFAMILIASALTERAR                    = 3;
$PER_CADASTROFAMILIASEXCLUIR                    = 4;

$PER_CADASTROMEMBROSFAMILIAS                    = 5;
$PER_CADASTROMEMBROSFAMILIASINSERIR             = 6;
$PER_CADASTROMEMBROSFAMILIASALTERAR             = 7;
$PER_CADASTROMEMBROSFAMILIASEXCLUIR             = 8;

$PER_CADASTROCARGOSPROFISSIONALSOCIAL           = 9;
$PER_CADASTROCARGOSPROFISSIONALSOCIALINSERIR    = 10;
$PER_CADASTROCARGOSPROFISSIONALSOCIALALTERAR    = 11;
$PER_CADASTROCARGOSPROFISSIONALSOCIALEXCLUIR    = 12;

$PER_CADASTROFORNECEDORES                       = 13;
$PER_CADASTROFORNECEDORESINSERIR                = 14;
$PER_CADASTROFORNECEDORESALTERAR                = 15;
$PER_CADASTROFORNECEDORESEXCLUIR                = 16;

$PER_CADASTRONATUREZAS                          = 17;
$PER_CADASTRONATUREZASINSERIR                   = 18;
$PER_CADASTRONATUREZASALTERAR                   = 19;
$PER_CADASTRONATUREZASEXCLUIR                   = 20;

$PER_CADASTROPROFISSIONALSOCIAL                 = 21;
$PER_CADASTROPROFISSIONALSOCIALINSERIR          = 22;
$PER_CADASTROPROFISSIONALSOCIALALTERAR          = 23;
$PER_CADASTROPROFISSIONALSOCIALEXCLUIR          = 24;

$PER_CADASTROUNIDADESSOCIAL                     = 25;
$PER_CADASTROUNIDADESSOCIALINSERIR              = 26;
$PER_CADASTROUNIDADESSOCIALALTERAR              = 27;
$PER_CADASTROUNIDADESSOCIALEXCLUIR              = 28;

$PER_CADASTROGRUPOSALMOXARIFADOS                = 29;
$PER_CADASTROGRUPOSALMOXARIFADOSINSERIR         = 30;
$PER_CADASTROGRUPOSALMOXARIFADOSALTERAR         = 31;
$PER_CADASTROGRUPOSALMOXARIFADOSEXCLUIR         = 32;

$PER_CADASTROUNIDADESALMOXARIFADOS              = 33;
$PER_CADASTROUNIDADESALMOXARIFADOSINSERIR       = 34;
$PER_CADASTROUNIDADESALMOXARIFADOSALTERAR       = 35;
$PER_CADASTROUNIDADESALMOXARIFADOSEXCLUIR       = 36;

$PER_CADASTROALMOXARIFADOS                      = 37;
$PER_CADASTROALMOXARIFADOSINSERIR               = 38;
$PER_CADASTROALMOXARIFADOSALTERAR               = 39;
$PER_CADASTROALMOXARIFADOSEXCLUIR               = 40;

$PER_CADASTROENTRADASALMOXARIFADOS              = 41;
$PER_CADASTROENTRADASALMOXARIFADOSINSERIR       = 42;
$PER_CADASTROENTRADASALMOXARIFADOSALTERAR       = 43;
$PER_CADASTROENTRADASALMOXARIFADOSEXCLUIR       = 44;

$PER_CADASTROSAIDASALMOXARIFADOS                = 45;
$PER_CADASTROSAIDASALMOXARIFADOSINSERIR         = 46;
$PER_CADASTROSAIDASALMOXARIFADOSALTERAR         = 47;
$PER_CADASTROSAIDASALMOXARIFADOSEXCLUIR         = 48;

$PER_CADASTROGRUPOSGENEROSALIMENTICIOS          = 49;
$PER_CADASTROGRUPOSGENEROSALIMENTICIOSINSERIR   = 50;
$PER_CADASTROGRUPOSGENEROSALIMENTICIOSALTERAR   = 51;
$PER_CADASTROGRUPOSGENEROSALIMENTICIOSEXCLUIR   = 52;

$PER_CADASTROUNIDADESGENEROSALIMENTICIOS        = 53;
$PER_CADASTROUNIDADESGENEROSALIMENTICIOSINSERIR = 54;
$PER_CADASTROUNIDADESGENEROSALIMENTICIOSALTERAR = 55;
$PER_CADASTROUNIDADESGENEROSALIMENTICIOSEXCLUIR = 56;

$PER_CADASTROGENEROSALIMENTICIOS                = 57;
$PER_CADASTROGENEROSALIMENTICIOSINSERIR         = 58;
$PER_CADASTROGENEROSALIMENTICIOSALTERAR         = 59;
$PER_CADASTROGENEROSALIMENTICIOSEXCLUIR         = 60;

$PER_CADASTROENTRADASGENEROSALIMENTICIOS        = 61;
$PER_CADASTROENTRADASGENEROSALIMENTICIOSINSERIR = 62;
$PER_CADASTROENTRADASGENEROSALIMENTICIOSALTERAR = 63;
$PER_CADASTROENTRADASGENEROSALIMENTICIOSEXCLUIR = 64;

$PER_CADASTROSAIDASGENEROSALIMENTICIOS          = 65;
$PER_CADASTROSAIDASGENEROSALIMENTICIOSINSERIR   = 66;
$PER_CADASTROSAIDASGENEROSALIMENTICIOSALTERAR   = 67;
$PER_CADASTROSAIDASGENEROSALIMENTICIOSEXCLUIR   = 68;

$PER_CADASTROGRUPOSMATERIAISDIDATICOS           = 69;
$PER_CADASTROGRUPOSMATERIAISDIDATICOSINSERIR    = 70;
$PER_CADASTROGRUPOSMATERIAISDIDATICOSALTERAR    = 71;
$PER_CADASTROGRUPOSMATERIAISDIDATICOSEXCLUIR    = 72;

$PER_CADASTROUNIDADESMATERIAISDIDATICOS         = 73;
$PER_CADASTROUNIDADESMATERIAISDIDATICOSINSERIR  = 74;
$PER_CADASTROUNIDADESMATERIAISDIDATICOSALTERAR  = 75;
$PER_CADASTROUNIDADESMATERIAISDIDATICOSEXCLUIR  = 76;

$PER_CADASTROMATERIAISDIDATICOS                 = 77;
$PER_CADASTROMATERIAISDIDATICOSINSERIR          = 78;
$PER_CADASTROMATERIAISDIDATICOSALTERAR          = 79;
$PER_CADASTROMATERIAISDIDATICOSEXCLUIR          = 80;

$PER_CADASTROENTRADASMATERIAISDIDATICOS         = 81;
$PER_CADASTROENTRADASMATERIAISDIDATICOSINSERIR  = 82;
$PER_CADASTROENTRADASMATERIAISDIDATICOSALTERAR  = 83;
$PER_CADASTROENTRADASMATERIAISDIDATICOSEXCLUIR  = 84;

$PER_CADASTROSAIDASMATERIAISDIDATICOS           = 85;
$PER_CADASTROSAIDASMATERIAISDIDATICOSINSERIR    = 86;
$PER_CADASTROSAIDASMATERIAISDIDATICOSALTERAR    = 87;
$PER_CADASTROSAIDASMATERIAISDIDATICOSEXCLUIR    = 88;

$PER_CADASTROUSUÁRIOS                           = 89;
$PER_CADASTROGRUPOSPERMISSÕES                   = 90;

$PER_CADASTROORGAOSSOCIAL						= 91;
$PER_CADASTROORGAOSSOCIALINSERIR				= 92;
$PER_CADASTROORGAOSSOCIALALTERAR				= 93;
$PER_CADASTROORGAOSSOCIALEXCLUIR				= 94;

$PER_CADASTROCAMPANHASSOCIAL					= 95;
$PER_CADASTROCAMPANHASSOCIALINSERIR				= 96;
$PER_CADASTROCAMPANHASSOCIALALTERAR				= 97;
$PER_CADASTROCAMPANHASSOCIALEXCLUIR				= 98;

$PER_CADASTROMOTIVOSATENDIMENTO					= 99;
$PER_CADASTROMOTIVOSATENDIMENTOINSERIR			= 100;
$PER_CADASTROMOTIVOSATENDIMENTOALTERAR			= 101;
$PER_CADASTROMOTIVOSATENDIMENTOEXCLUIR			= 102;

$PER_CADASTROATENDIMENTOS					    = 103;
$PER_CADASTROATENDIMENTOSINSERIR			    = 104;
$PER_CADASTROATENDIMENTOSALTERAR			    = 105;
$PER_CADASTROATENDIMENTOSEXCLUIR			    = 106;

?>